"use client";

import MotivationalToastProvider from "@/components/motivational-toaster-provider";
import { SessionProvider } from "next-auth/react";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <head>
          <title>BioVerse Medical App</title>
          <meta name="description" content="Generated by create next app" />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
        >
          <MotivationalToastProvider />
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
